application: guillotine-cuts
version: 1
runtime: go
api_version: go1

handlers:

- url: /_ah/spi/.*
  script: _go_app

- url: /
  static_files: client/index.html
  upload: client/index.html

- url: /
  static_dir: client/


